# Generated by Django 2.1.3 on 2018-11-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='org_category',
            field=models.CharField(choices=[('training_institution', '培训机构'), ('university', '高校'), ('person', '个人')], default='university', max_length=20, verbose_name='机构类别'),
        ),
    ]
