# Generated by Django 2.1.3 on 2018-11-13 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='课程名称')),
                ('course_img', models.ImageField(upload_to='Banner/%Y/%m', verbose_name='课程图片')),
                ('course_desc', models.CharField(max_length=200, null=True, verbose_name='课程描述')),
                ('course_details', models.TextField(verbose_name='课程详情')),
                ('course_degree', models.CharField(choices=[('low_rank', '初级'), ('middle_rank', '中级'), ('high_rank', '高级')], max_length=10, null=True, verbose_name='难度')),
                ('course_duration', models.IntegerField(default=0, verbose_name='课程时长')),
                ('course_created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('learning_nums', models.IntegerField(default=0, verbose_name='学习人数')),
                ('favor_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击量')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=100, verbose_name='资源名称')),
                ('resource_created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='下载资源')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=20, verbose_name='章节名称')),
                ('section_created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
        migrations.CreateModel(
            name='Vedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vedio_name', models.CharField(max_length=50, verbose_name='视频名称')),
                ('vedio_created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Section', verbose_name='章节')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
    ]
